### ISSUE TITLE
Valid syntax is wrongly parsed 

### ISSUE THREAD

**Issue by ibc** [substack/brfs#47]
The following valid code fails to parse when `brfs` is used within a browserify `transform`:

`css.js`:
```javascript
var
	/**
	 * Dependencies.
	 */
	fs = require('fs'),

	/**
	 * Local variables.
	 */
	style = fs.readFileSync(__dirname + '/assets/css/style.css', 'utf8');


module.exports = function () {
	var
		tag = document.createElement('style'),
		content = document.createTextNode(style);

	tag.appendChild(content);
	document.body.appendChild(tag);
};
```

When running a `gulp` task as follows it fails:

```javascript
gulp.task('browserify', function () {
	return browserify([path.join(__dirname, PKG.main)], {
		standalone: PKG.name
	})
		.transform('brfs')
		.bundle()
		.pipe(vinyl_source_stream(PKG.name + '.js'))
		.pipe(filelog('browserify'))
		.pipe(gulp.dest('dist/'));
});
```

Output:
```
[11:44:01] 'browserify' errored after 198 ms
[11:44:01] Error:
/Users/ibc/src/someapp/lib/css.js:4
module.exports = function () {
      ^
ParseError: Unexpected token
    at formatError (/Users/ibc/.npm-packages/lib/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.1/formatError.js:20:10)
    at Gulp.<anonymous> (/Users/ibc/.npm-packages/lib/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.1/log/events.js:26:15)
    at Gulp.emit (events.js:107:17)
    at Object.error (/Users/ibc/src/someapp/node_modules/gulp/node_modules/undertaker/lib/helpers/createExtensions.js:58:10)
    at handler (/Users/ibc/src/someapp/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/lib/mapSeries.js:43:14)
    at f (/Users/ibc/src/someapp/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/node_modules/once/once.js:17:25)
    at f (/Users/ibc/src/someapp/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/node_modules/once/once.js:17:25)
    at done (/Users/ibc/src/someapp/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:26:12)
    at Domain.onError (/Users/ibc/src/someapp/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:34:12)
    at Domain.g (events.js:199:16)
```

* brfs 1.4.0
* browserify 10.2.4

**Comment by dokuboyejo** [comment]
Having same issue.
Has this been resolved?

**Comment by ibc** [comment]
Not even replied. This project is dead.

**Comment by mattdesl** [comment]
I've added a failing test. Tracking upstream in this issue:
https://github.com/substack/static-module/issues/18

**Comment by mattdesl** [comment]
Ok, it was just me being dumb, thanks to @eush77's PR this should no longer be a problem in static-module/brfs. :smile:

**Comment by dokuboyejo** [comment]
Thanks @mattdesl 
Has the PR been promoted to current release or we should await its release soon

**Comment by mattdesl** [comment]
@dokuboyejo The PR was pushed in `static-module@1.3.0` so `brfs` does not need to update.

You can get the latest dependencies by doing this:

```sh
npm install brfs --save-dev
``` 

It should re-install the dependencies including `static-module@1.3.0`. :smile:
