### ISSUE TITLE
Fatal error: Cannot find module './lib/_stream_transform.js'

### ISSUE THREAD

**Issue by ccorcos** [substack/brfs#58]
```
Fatal error: Cannot find module './lib/_stream_transform.js'
    Error: Cannot find module './lib/_stream_transform.js'
      at Function.Module._resolveFilename (module.js:336:15)
      at Function.Module._load (module.js:278:25)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (/Users/chetcorcos/code/web-ux/node_modules/brfs/node_modules/through2/node_modules/readable-stream/transform.js:1:80)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (/Users/chetcorcos/code/web-ux/node_modules/brfs/node_modules/through2/through2.js:1:79)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (/Users/chetcorcos/code/web-ux/node_modules/brfs/node_modules/static-module/index.js:4:15)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (/Users/chetcorcos/code/web-ux/node_modules/brfs/index.js:1:82)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at nr (/Users/chetcorcos/code/web-ux/node_modules/grunt-browserify/node_modules/browserify/node_modules/module-deps/index.js:280:21)
      at /Users/chetcorcos/code/web-ux/node_modules/grunt-browserify/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:44:21
      at ondir (/Users/chetcorcos/code/web-ux/node_modules/grunt-browserify/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:187:31)
      at /Users/chetcorcos/code/web-ux/node_modules/grunt-browserify/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:153:39
      at onex (/Users/chetcorcos/code/web-ux/node_modules/grunt-browserify/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:93:22)
      at /Users/chetcorcos/code/web-ux/node_modules/grunt-browserify/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:24:18
      at FSReqWrap.oncomplete (fs.js:99:15)

```

**Comment by ccorcos** [comment]
deleted node_modules and reinstalled everything and it seems to work
